Fix runtime loader error on ubuntu 13.04/14.04
The ubuntu linker expects the library arguments to be ordered in a
certain way.

Otherwise WorkflowFetch.fe could not run due to unknown symbol from the
ssl library referenced by cmail.so:

  $ ferite --fe-use-jedi /cention/services/WorkflowFetch.fe
  [ferite: compile]
  Error: Library Loader: /cention/lib/ferite/module-native/cmail.so: undefined symbol: SSL_state
  Error: Can't compile included file "/cention/lib/ferite/module-source/cmail.fec", error on line 1
  Error: Unable to find module 'cmail'
  Error: Can't compile included file "/cention/services/Scripts.feh", error on line 7
  Error: Unable to find module 'Scripts'
  Error: Fatal error compiling script "/cention/services/WorkflowFetch.fe"

With this change cmail is buildable and usable on recent Ubuntu releases
13.04 and 14.04.